version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  dribblematch:
    image: juhyunpark/dribblematch
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - ./dribbleMatch-prod.env
    volumes:
      - /Users/juyunpark/Desktop/dmimage:/app/images