spring:
  profiles:
    active:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/dribbleMatch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret-key: ${SECRET_KEY}
    access-token-expire: ${ACCESS_TOKEN_EXPIRE_LENGTH}
    refresh-token-expire: ${REFRESH_TOKEN_EXPIRE_LENGTH}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  batch:
    jdbc:
      initialize-schema: always
    path:
      region-csv-path: ${REGION_CSV_PATH}